// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/adept/api/v1"
)

// ActionStatusApplyConfiguration represents a declarative configuration of the ActionStatus type for use
// with apply.
type ActionStatusApplyConfiguration struct {
	Phase   *apiv1.ActionPhase `json:"phase,omitempty"`
	JobName *string            `json:"jobName,omitempty"`
	// Message explains a Failed phase caused by a spec or claim problem.
	Message *string `json:"message,omitempty"`
}

// ActionStatusApplyConfiguration constructs a declarative configuration of the ActionStatus type for use with
// apply.
func ActionStatus() *ActionStatusApplyConfiguration {
	return &ActionStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ActionStatusApplyConfiguration) WithPhase(value apiv1.ActionPhase) *ActionStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithJobName sets the JobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobName field is set to the value of the last call.
func (b *ActionStatusApplyConfiguration) WithJobName(value string) *ActionStatusApplyConfiguration {
	b.JobName = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ActionStatusApplyConfiguration) WithMessage(value string) *ActionStatusApplyConfiguration {
	b.Message = &value
	return b
}
