// Code generated by controller-gen. DO NOT EDIT.

package v1

// ActionSpecApplyConfiguration represents a declarative configuration of the ActionSpec type for use
// with apply.
//
// ActionSpec triggers a ritual Definition.
type ActionSpecApplyConfiguration struct {
	// Type names the Definition (in the instance namespace) to execute.
	Type *string `json:"type,omitempty"`
	// Claim identifies the service instance; with ApiVersion and Kind it
	// derives the instance namespace when the Action lives in a claim
	// namespace.
	Claim *string `json:"claim,omitempty"`
	// ApiVersion is the claim's apiVersion ("group/version"). Required
	// together with Kind when the Action lives in a claim namespace.
	ApiVersion *string `json:"apiVersion,omitempty"`
	// Kind is the claim's kind. Required together with ApiVersion when the
	// Action lives in a claim namespace.
	Kind *string `json:"kind,omitempty"`
	// Args are made available to the job. Stored, not injected for now.
	Args map[string]string `json:"args,omitempty"`
}

// ActionSpecApplyConfiguration constructs a declarative configuration of the ActionSpec type for use with
// apply.
func ActionSpec() *ActionSpecApplyConfiguration {
	return &ActionSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ActionSpecApplyConfiguration) WithType(value string) *ActionSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithClaim sets the Claim field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Claim field is set to the value of the last call.
func (b *ActionSpecApplyConfiguration) WithClaim(value string) *ActionSpecApplyConfiguration {
	b.Claim = &value
	return b
}

// WithApiVersion sets the ApiVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApiVersion field is set to the value of the last call.
func (b *ActionSpecApplyConfiguration) WithApiVersion(value string) *ActionSpecApplyConfiguration {
	b.ApiVersion = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ActionSpecApplyConfiguration) WithKind(value string) *ActionSpecApplyConfiguration {
	b.Kind = &value
	return b
}

// WithArgs puts the entries into the Args field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Args field,
// overwriting an existing map entries in Args field with the same key.
func (b *ActionSpecApplyConfiguration) WithArgs(entries map[string]string) *ActionSpecApplyConfiguration {
	if b.Args == nil && len(entries) > 0 {
		b.Args = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Args[k] = v
	}
	return b
}
