// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	batchv1 "k8s.io/api/batch/v1"
)

// DefinitionSpecApplyConfiguration represents a declarative configuration of the DefinitionSpec type for use
// with apply.
//
// DefinitionSpec defines a ritual: a job template executed on demand.
type DefinitionSpecApplyConfiguration struct {
	// Description of what this ritual does.
	Description *string `json:"description,omitempty"`
	// JobTemplate is instantiated as a Job each time the ritual runs.
	JobTemplate *batchv1.JobTemplateSpec `json:"jobTemplate,omitempty"`
}

// DefinitionSpecApplyConfiguration constructs a declarative configuration of the DefinitionSpec type for use with
// apply.
func DefinitionSpec() *DefinitionSpecApplyConfiguration {
	return &DefinitionSpecApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *DefinitionSpecApplyConfiguration) WithDescription(value string) *DefinitionSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithJobTemplate sets the JobTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobTemplate field is set to the value of the last call.
func (b *DefinitionSpecApplyConfiguration) WithJobTemplate(value batchv1.JobTemplateSpec) *DefinitionSpecApplyConfiguration {
	b.JobTemplate = &value
	return b
}
