// Code generated by controller-gen. DO NOT EDIT.

package v1

// MaintenanceStatusApplyConfiguration represents a declarative configuration of the MaintenanceStatus type for use
// with apply.
//
// MaintenanceStatus reports the schedule this instance resolved to.
type MaintenanceStatusApplyConfiguration struct {
	// Schedule is the cron expression this instance runs on, including its
	// offset within the window.
	Schedule *string `json:"schedule,omitempty"`
	// ObservedGeneration is the spec generation the schedule was computed
	// from.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// CronJobName is the CronJob executing the schedule, in this namespace.
	CronJobName *string `json:"cronJobName,omitempty"`
	// Message explains why no schedule could be resolved.
	Message *string `json:"message,omitempty"`
}

// MaintenanceStatusApplyConfiguration constructs a declarative configuration of the MaintenanceStatus type for use with
// apply.
func MaintenanceStatus() *MaintenanceStatusApplyConfiguration {
	return &MaintenanceStatusApplyConfiguration{}
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *MaintenanceStatusApplyConfiguration) WithSchedule(value string) *MaintenanceStatusApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MaintenanceStatusApplyConfiguration) WithObservedGeneration(value int64) *MaintenanceStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithCronJobName sets the CronJobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CronJobName field is set to the value of the last call.
func (b *MaintenanceStatusApplyConfiguration) WithCronJobName(value string) *MaintenanceStatusApplyConfiguration {
	b.CronJobName = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *MaintenanceStatusApplyConfiguration) WithMessage(value string) *MaintenanceStatusApplyConfiguration {
	b.Message = &value
	return b
}
