// Code generated by controller-gen. DO NOT EDIT.

package v1

// MaintenanceDefinitionStatusApplyConfiguration represents a declarative configuration of the MaintenanceDefinitionStatus type for use
// with apply.
//
// MaintenanceDefinitionStatus reports the schedule this instance resolved to.
type MaintenanceDefinitionStatusApplyConfiguration struct {
	// Schedule is the cron expression this instance runs on, including its
	// offset within the window.
	Schedule *string `json:"schedule,omitempty"`
	// ObservedGeneration is the spec generation the schedule was computed
	// from.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
	// CronJobName is the CronJob executing the schedule, in this namespace.
	CronJobName *string `json:"cronJobName,omitempty"`
	// Message explains why no schedule could be resolved.
	Message *string `json:"message,omitempty"`
}

// MaintenanceDefinitionStatusApplyConfiguration constructs a declarative configuration of the MaintenanceDefinitionStatus type for use with
// apply.
func MaintenanceDefinitionStatus() *MaintenanceDefinitionStatusApplyConfiguration {
	return &MaintenanceDefinitionStatusApplyConfiguration{}
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *MaintenanceDefinitionStatusApplyConfiguration) WithSchedule(value string) *MaintenanceDefinitionStatusApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *MaintenanceDefinitionStatusApplyConfiguration) WithObservedGeneration(value int64) *MaintenanceDefinitionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithCronJobName sets the CronJobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CronJobName field is set to the value of the last call.
func (b *MaintenanceDefinitionStatusApplyConfiguration) WithCronJobName(value string) *MaintenanceDefinitionStatusApplyConfiguration {
	b.CronJobName = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *MaintenanceDefinitionStatusApplyConfiguration) WithMessage(value string) *MaintenanceDefinitionStatusApplyConfiguration {
	b.Message = &value
	return b
}
