// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/adept/api/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MaintenanceWindowSpecApplyConfiguration represents a declarative configuration of the MaintenanceWindowSpec type for use
// with apply.
//
// MaintenanceWindowSpec declares a recurring window in which maintenance may
// start. The window opens at Time on each day listed in DaysOfWeek, read as wall
// clock in TimeZone, and stays open for Duration.
//
// Instances sharing a window are spread across the window by an offset derived
// from the instance, so a window governing many instances does not start all
// of them at once. Maintenance that has started is never interrupted by the
// window closing.
type MaintenanceWindowSpecApplyConfiguration struct {
	// DaysOfWeek are the days a window starts on, with no repeats. A window
	// running past midnight ends on the following day, which need not be
	// listed here.
	DaysOfWeek []apiv1.Day `json:"daysOfWeek,omitempty"`
	// Time is the wall-clock start of the window in TimeZone, "HH:MM" in
	// 24-hour form, for example "22:00".
	Time *string `json:"time,omitempty"`
	// Duration is the time span during which maintenance may start, between 1h and
	// 24h. Instances sharing a window are spread across it so they do not all
	// start at once.
	//
	// It does not bound how long maintenance runs. A run that starts inside
	// the window keeps going until it finishes, which may be well after the window
	// has closed.
	Duration *metav1.Duration `json:"duration,omitempty"`
	// TimeZone is the IANA zone name the window's Time is read in, for example
	// "Europe/Zurich". Defaults to UTC.
	TimeZone *string `json:"timeZone,omitempty"`
	// Default marks this window as the one instances take when they name no
	// window of their own. At most one window may be the default; a second
	// one claiming it is rejected.
	Default *bool `json:"default,omitempty"`
}

// MaintenanceWindowSpecApplyConfiguration constructs a declarative configuration of the MaintenanceWindowSpec type for use with
// apply.
func MaintenanceWindowSpec() *MaintenanceWindowSpecApplyConfiguration {
	return &MaintenanceWindowSpecApplyConfiguration{}
}

// WithDaysOfWeek adds the given value to the DaysOfWeek field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DaysOfWeek field.
func (b *MaintenanceWindowSpecApplyConfiguration) WithDaysOfWeek(values ...apiv1.Day) *MaintenanceWindowSpecApplyConfiguration {
	for i := range values {
		b.DaysOfWeek = append(b.DaysOfWeek, values[i])
	}
	return b
}

// WithTime sets the Time field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Time field is set to the value of the last call.
func (b *MaintenanceWindowSpecApplyConfiguration) WithTime(value string) *MaintenanceWindowSpecApplyConfiguration {
	b.Time = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *MaintenanceWindowSpecApplyConfiguration) WithDuration(value metav1.Duration) *MaintenanceWindowSpecApplyConfiguration {
	b.Duration = &value
	return b
}

// WithTimeZone sets the TimeZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeZone field is set to the value of the last call.
func (b *MaintenanceWindowSpecApplyConfiguration) WithTimeZone(value string) *MaintenanceWindowSpecApplyConfiguration {
	b.TimeZone = &value
	return b
}

// WithDefault sets the Default field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Default field is set to the value of the last call.
func (b *MaintenanceWindowSpecApplyConfiguration) WithDefault(value bool) *MaintenanceWindowSpecApplyConfiguration {
	b.Default = &value
	return b
}
