// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	apiv1 "github.com/helmetica-framework/adept/api/v1"
	internal "github.com/helmetica-framework/adept/applyconfiguration/internal"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// MaintenanceDefinitionApplyConfiguration represents a declarative configuration of the MaintenanceDefinition type for use
// with apply.
//
// MaintenanceDefinition is one instance's maintenance schedule. It lives in
// the instance namespace, names a MaintenanceWindow to run in and a Definition
// to run, and produces the CronJob that fires it.
type MaintenanceDefinitionApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:",inline"`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                                 *MaintenanceDefinitionSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                               *MaintenanceDefinitionStatusApplyConfiguration `json:"status,omitempty"`
}

// MaintenanceDefinition constructs a declarative configuration of the MaintenanceDefinition type for use with
// apply.
func MaintenanceDefinition(name, namespace string) *MaintenanceDefinitionApplyConfiguration {
	b := &MaintenanceDefinitionApplyConfiguration{}
	b.WithName(name)
	b.WithNamespace(namespace)
	b.WithKind("MaintenanceDefinition")
	b.WithAPIVersion("rituals.helmetica.io/v1")
	return b
}

// ExtractMaintenanceDefinitionFrom extracts the applied configuration owned by fieldManager from
// maintenanceDefinition for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// maintenanceDefinition must be a unmodified MaintenanceDefinition API object that was retrieved from the Kubernetes API.
// ExtractMaintenanceDefinitionFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractMaintenanceDefinitionFrom(maintenanceDefinition *apiv1.MaintenanceDefinition, fieldManager string, subresource string) (*MaintenanceDefinitionApplyConfiguration, error) {
	b := &MaintenanceDefinitionApplyConfiguration{}
	err := managedfields.ExtractInto(maintenanceDefinition, internal.Parser().Type("com.github.helmetica-framework.adept.api.v1.MaintenanceDefinition"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(maintenanceDefinition.Name)
	b.WithNamespace(maintenanceDefinition.Namespace)

	b.WithKind("MaintenanceDefinition")
	b.WithAPIVersion("rituals.helmetica.io/v1")
	return b, nil
}

// ExtractMaintenanceDefinition extracts the applied configuration owned by fieldManager from
// maintenanceDefinition. If no managedFields are found in maintenanceDefinition for fieldManager, a
// MaintenanceDefinitionApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// maintenanceDefinition must be a unmodified MaintenanceDefinition API object that was retrieved from the Kubernetes API.
// ExtractMaintenanceDefinition provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractMaintenanceDefinition(maintenanceDefinition *apiv1.MaintenanceDefinition, fieldManager string) (*MaintenanceDefinitionApplyConfiguration, error) {
	return ExtractMaintenanceDefinitionFrom(maintenanceDefinition, fieldManager, "")
}

// ExtractMaintenanceDefinitionStatus extracts the applied configuration owned by fieldManager from
// maintenanceDefinition for the status subresource.
func ExtractMaintenanceDefinitionStatus(maintenanceDefinition *apiv1.MaintenanceDefinition, fieldManager string) (*MaintenanceDefinitionApplyConfiguration, error) {
	return ExtractMaintenanceDefinitionFrom(maintenanceDefinition, fieldManager, "status")
}

func (b MaintenanceDefinitionApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithKind(value string) *MaintenanceDefinitionApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithAPIVersion(value string) *MaintenanceDefinitionApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithName(value string) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithGenerateName(value string) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithNamespace(value string) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithUID(value types.UID) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithResourceVersion(value string) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithGeneration(value int64) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithCreationTimestamp(value apismetav1.Time) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithDeletionTimestamp(value apismetav1.Time) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *MaintenanceDefinitionApplyConfiguration) WithLabels(entries map[string]string) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *MaintenanceDefinitionApplyConfiguration) WithAnnotations(entries map[string]string) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *MaintenanceDefinitionApplyConfiguration) WithOwnerReferences(values ...*metav1.OwnerReferenceApplyConfiguration) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *MaintenanceDefinitionApplyConfiguration) WithFinalizers(values ...string) *MaintenanceDefinitionApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *MaintenanceDefinitionApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &metav1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithSpec(value *MaintenanceDefinitionSpecApplyConfiguration) *MaintenanceDefinitionApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *MaintenanceDefinitionApplyConfiguration) WithStatus(value *MaintenanceDefinitionStatusApplyConfiguration) *MaintenanceDefinitionApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *MaintenanceDefinitionApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *MaintenanceDefinitionApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *MaintenanceDefinitionApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *MaintenanceDefinitionApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
