// Code generated by controller-gen. DO NOT EDIT.

package v1

// MaintenanceSpecApplyConfiguration represents a declarative configuration of the MaintenanceSpec type for use
// with apply.
//
// MaintenanceSpec schedules one instance's maintenance. Every field is
// optional: an empty spec is a complete schedule, running the maintenance
// ritual in the operator's default window.
type MaintenanceSpecApplyConfiguration struct {
	// Window names the MaintenanceWindow this instance's maintenance starts
	// in. Empty takes the window the operator marked as the default.
	Window *string `json:"window,omitempty"`
	// Ritual names the Definition to run, in this namespace.
	Ritual *string `json:"ritual,omitempty"`
	// Suspend stops maintenance for this instance. Its schedule stays in
	// place and stays visible.
	Suspend *bool `json:"suspend,omitempty"`
}

// MaintenanceSpecApplyConfiguration constructs a declarative configuration of the MaintenanceSpec type for use with
// apply.
func MaintenanceSpec() *MaintenanceSpecApplyConfiguration {
	return &MaintenanceSpecApplyConfiguration{}
}

// WithWindow sets the Window field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Window field is set to the value of the last call.
func (b *MaintenanceSpecApplyConfiguration) WithWindow(value string) *MaintenanceSpecApplyConfiguration {
	b.Window = &value
	return b
}

// WithRitual sets the Ritual field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ritual field is set to the value of the last call.
func (b *MaintenanceSpecApplyConfiguration) WithRitual(value string) *MaintenanceSpecApplyConfiguration {
	b.Ritual = &value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *MaintenanceSpecApplyConfiguration) WithSuspend(value bool) *MaintenanceSpecApplyConfiguration {
	b.Suspend = &value
	return b
}
