// Code generated by controller-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1 "github.com/helmetica-framework/adept/api/v1"
	apiv1 "github.com/helmetica-framework/adept/applyconfiguration/api/v1"
	internal "github.com/helmetica-framework/adept/applyconfiguration/internal"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=rituals.helmetica.io, Version=v1
	case v1.SchemeGroupVersion.WithKind("Action"):
		return &apiv1.ActionApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ActionSpec"):
		return &apiv1.ActionSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("ActionStatus"):
		return &apiv1.ActionStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("Definition"):
		return &apiv1.DefinitionApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DefinitionSpec"):
		return &apiv1.DefinitionSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MaintenanceDefinition"):
		return &apiv1.MaintenanceDefinitionApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MaintenanceDefinitionSpec"):
		return &apiv1.MaintenanceDefinitionSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MaintenanceDefinitionStatus"):
		return &apiv1.MaintenanceDefinitionStatusApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MaintenanceWindow"):
		return &apiv1.MaintenanceWindowApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("MaintenanceWindowSpec"):
		return &apiv1.MaintenanceWindowSpecApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
