resources:
- bases/rituals.helmetica.io_definitions.yaml
- bases/rituals.helmetica.io_actions.yaml
- bases/rituals.helmetica.io_maintenancewindows.yaml
#+kubebuilder:scaffold:crdkustomizeresource

configurations:
- kustomizeconfig.yaml
